### ISSUE TITLE
경로수정

### ISSUE THREAD

**Issue by ShinYeJeong** [DoA-Jo/Choco-Buy#1]
Trade.jsp 에서

채팅으로거래하기 버튼 onclick 경로
onclick="location.href='/Chat/ChatMyRoom?trade_seq=${trade.trade_seq}'"
->onclick="location.href='/Chat/Chat?trade_seq=${trade.trade_seq}'"
으로 변경 해야합니다

**Comment by msh428** [comment]
수정 했습니다
