### ISSUE TITLE
안녕하세요 수정입니다 

### ISSUE THREAD

**Issue by gerald119** [DoA-Jo/Choco-Buy#2]
안녕하세요 최재현 입니다 
착오 드려 죄송합니다 

**********UserServiceImpl.java  파일 에서  88 번째줄 *********

public void updateMypageUserArea(UserVO vo) {       => 아래와 같이 수정해주세요 User 가 아니고 Use 입니다 

public void updateMypageUseArea(UserVO vo) {               

*********그리고 UserDAOMybatis.java 파일에서   아래 메서드 추가 부탁드립니다 *********

	// 주소 검색후 저장 
	public int updateMypageUseArea(UserVO vo) {
		System.out.println("===> JDBC로 updateMypageUser() 기능 처리");
		return mybatis.update("UserDAO.updateMypageUseArea", vo);
	}

**Comment by msh428** [comment]
수정, 추가 완료 했습니다
